### ISSUE TITLE
move to recast community

### ISSUE THREAD

**Issue by cranmer** [waynemot/recastTest#1]
1) add @lukasheinrich and @cranmer as collaborators to the repository
2) we can move it to recast community
3) rename repo to recast-frontend-tests

**Comment by cranmer** [comment]
I got the invite, but I guess only you can rename and transfer ownership.

click Settings tab on right: and then at the at bottom
![transfer](https://cloud.githubusercontent.com/assets/4458890/8236896/68a6ffc2-15a0-11e5-8888-fde09e481c24.png)

**Comment by waynemot** [comment]
I've found no way to transfer ownership to the new 'recast-testing' group after repeated attempts.  I've wrote a message to github's support to find out how to transfer the project.

**Comment by waynemot** [comment]
OK, transfer and rename complete.   Closing this issue.
